server:
  port: 80


spring:
  application:
    name: trade-api
  redis:
    host: 127.0.0.1
    database: 0
    password:
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-idle: 100
        max-wait: 1000
        min-idle: 5
    timeout: 1000
