spring:
  messages:
    encoding: UTF-8
    cache-duration: 3600 # 加载国际化文件的缓存时间，单位为秒，默认为永久缓存
    basename: i18n/messages,i18n/login
    fallback-to-system-locale: false # 当找不到当前语言的资源文件时,如果为true默认找当前系统的语言对应的资源文件，如果为false即加载系统默认的如messages.properties文件
    always-use-message-format: false # MessageFormat定义了如何展示信息的格式；默认：false